name: livin_clone

packages:
  - libraries/**
  - features/**
  - "*"

scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages
  unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run all Flutter tests in this project.
  unit_test_and_coverage:
    description: Merge all packages coverage tracefiles ignoring data related to generated files.
    run: 
      melos exec rmdir coverage
      melos run unit_test
      melos exec -c 1 --file-exists=coverage/lcov.info -- coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart
      coverde value -i coverage/filtered.lcov.info > MELOS_ROOT_PATH/coverage/result.txt
  build_runner:
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Run `build runner` in all packages
  pub_get:
    run: melos exec -- flutter pub get
    description: Run `pub get` in all packages
  flutter_clean:
    run: melos exec -- flutter clean
    description: Run `flutter clean` in all packages