name: livin_clone

packages:
  - libraries/*
  - features/*
  - shared/*
  - "*"

scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages
  unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run all Flutter tests in this project.
  unit_test_and_coverage:
    description: Merge all packages coverage tracefiles ignoring data related to generated files.
    run: 
      melos exec rmdir coverage
      melos run unit_test
      melos exec -c 1 --file-exists=coverage/lcov.info -- coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --filters \.g\.dart
      coverde value -i coverage/filtered.lcov.info > MELOS_ROOT_PATH/coverage/result.txt
  build_runner:
    description: Run `build runner` in packages
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  gen:
    description: Run 'asset generator' in gen package
    exec: fluttergen -c pubspec.yaml
    packageFilters:
      scope: "*gen*"
  