name: livin_clone
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  ui:
    path: libraries/ui
  core:
    path: libraries/core
  register:
    path: features/register
  localizations:
    path: shared/localizations
  dependencies:
    path: shared/dependencies
  config:
    path: shared/config
  gen:
    path: shared/gen
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  melos: ^3.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/translations/