name: livin_clone
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  ui:
    path: libraries/ui
  shared:
    path: libraries/shared
  core:
    path: libraries/core
  register:
    path: features/register
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  melos: ^3.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/translations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_italic.ttf
          style: italic
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 500
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
    - family: Batik
      fonts:
        - asset: assets/fonts/telkomsel_batik_sans_regular.ttf
        - asset: assets/fonts/telkomsel_batik_sans_bold.ttf
          weight: 700